export const reelsData = [
  {
    id: 1,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250747/da-tieng-trung/azxzxlqoucib4wy5wqlr.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 2,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250751/da-tieng-trung/al4kcghyjgrdthejnzs0.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 3,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250755/da-tieng-trung/kp1bkqwoetm1mcbtkxlm.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 4,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250760/da-tieng-trung/ugp1v4t7vu77j22fd86z.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 5,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250765/da-tieng-trung/ea8eirjiqqlrp0aeaziw.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 6,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250771/da-tieng-trung/vpxma3uljwapuea1gdcm.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 7,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250777/da-tieng-trung/kw87piqxxtc1jchssnby.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 8,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250892/da-tieng-trung/arf8vo1hjosfdix639sv.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 9,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250897/da-tieng-trung/sydathc0dvdjf6591ohp.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 10,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250902/da-tieng-trung/oiujkohgva7whbhbj3uq.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 11,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250907/da-tieng-trung/adipjcfwc2obadfoqqdk.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 12,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250912/da-tieng-trung/ut3zgiu9mznvsrs3nefe.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 13,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250916/da-tieng-trung/mma9hmgmyky9q0dsen2a.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 14,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250921/da-tieng-trung/nrcpbyuunxuxr8b55wvu.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 15,
    tab: "1",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785250925/da-tieng-trung/u5r7vnn4jzkitrjjubwd.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 16,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785284267/da-tieng-trung/arlgr60javojqgobuimi.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 17,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785284270/da-tieng-trung/uwpjjkf2s3cqnh15lf1w.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 18,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785284275/da-tieng-trung/ogfuvzynmnxmrr5mnewl.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 20,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785284534/da-tieng-trung/cp4cj166vjicf12xmx4p.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 21,
    tab: "5",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785285445/da-tieng-trung/obckg5hqfiey8m4lphbv.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 22,
    tab: "5",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785285451/da-tieng-trung/dfw4h8e99ketudiolgdh.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 23,
    tab: "5",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785285458/da-tieng-trung/ddw5da0em2hcukbpz7sl.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 24,
    tab: "4",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785286630/da-tieng-trung/ihbsaafrbxul4iuogckf.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 25,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291405/da-tieng-trung/jisambs5jjczjv5chy2x.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 26,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291410/da-tieng-trung/vdzum9u8dyedihebtudv.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 27,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291414/da-tieng-trung/dncxyiblnxh6wqu6ljqy.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 28,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291419/da-tieng-trung/dwl9cfyfunrtoiniuyb6.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 29,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291424/da-tieng-trung/u7z84rf2gqxlovfmn2hv.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 30,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291428/da-tieng-trung/qinkezo6pcy7csyqbovj.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 31,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291433/da-tieng-trung/hu2hyqbsu9doepdrdioo.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 32,
    tab: "2",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291666/da-tieng-trung/mcsi2slcfybqofe14bzr.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 33,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291808/da-tieng-trung/elkzp1yomkcpkafaw956.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 34,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291813/da-tieng-trung/obdaudxfrm7d9ruzbtny.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 35,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291817/da-tieng-trung/hyuuquagilwqegmwekxi.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 36,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291822/da-tieng-trung/aphwy23ydlmwk1tm6tzm.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 37,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291826/da-tieng-trung/gptciq4qxcrsxouwiatt.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 38,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291831/da-tieng-trung/wcewgav5kfe7v6lqoik5.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 39,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785291837/da-tieng-trung/b1j2wgfdu0nl1urer3hi.mp4",
    views: "0",
    likes: "0"
  },
  {
    id: 40,
    tab: "3",
    title: "",
    pinyin: "",
    vietnamese: "",
    image: "", 
    videoUrl: "https://res.cloudinary.com/zopjocdi/video/upload/v1785292181/da-tieng-trung/jdh72yrgzwxc3hut7ewe.mp4",
    views: "0",
    likes: "0"
  }
];
